#### general settings
<<<<<<< HEAD
name: EPCE-HDR-1e-6
=======
name: Final_Ours-Original
>>>>>>> a9f4214f96656ec01266916956474969d63a8ee5
model: condition
use_tb_logger: true
distortion: sr
scale: 1
<<<<<<< HEAD
gpu_ids: [4,5,6,7]
=======
gpu_ids: [0,1,2,3,4,5,6,7]
>>>>>>> a9f4214f96656ec01266916956474969d63a8ee5

#### datasets
datasets:
  train:
    name: Single_LDR2HDR
    mode: LQGT_condition_Val
<<<<<<< HEAD
    dataroot_LQ: /remote-home/share/jiaqi2/HDR/MultiTMCurvesDataset/LDR/Train_mu
    dataroot_GT: /remote-home/share/jiaqi2/HDR/MultiTMCurvesDataset/HDR/Train
    dataroot_ratio: /remote-home/share/jiaqi2/HDR/MultiTMCurvesDataset/alignratio/alignratio_Train
    use_shuffle: true
    n_workers: 8
    batch_size: 4
=======
    dataroot_LQ: /home/jiaqitang/HDR_all/A_Dataset/Subset_NTIRE/Train/image
    dataroot_GT: /home/jiaqitang/HDR_all/A_Dataset/Subset_NTIRE/Train/GT
    dataroot_ratio: /home/jiaqitang/HDR_all/A_Dataset/Subset_NTIRE/Train/alignratio
    use_shuffle: true
    n_workers: 8
    batch_size: 8
>>>>>>> a9f4214f96656ec01266916956474969d63a8ee5
    GT_size: 256
    use_flip: true
    use_rot: true
    condition: image
  val:
    name: Single_LDR2HDR
    mode: LQGT_condition_Val
<<<<<<< HEAD
    dataroot_LQ: /remote-home/share/jiaqi2/HDR/MultiTMCurvesDataset/LDR/Val_testgamma
    dataroot_GT: /remote-home/share/jiaqi2/HDR/MultiTMCurvesDataset/HDR/Val
    dataroot_ratio: /remote-home/share/jiaqi2/HDR/MultiTMCurvesDataset/alignratio/alignratio_Val
=======
    dataroot_LQ: /home/jiaqitang/HDR_all/A_Dataset/Subset_NTIRE/Val/image 
    dataroot_GT: /home/jiaqitang/HDR_all/A_Dataset/Subset_NTIRE/Val/GT
    dataroot_ratio: /home/jiaqitang/HDR_all/A_Dataset/Subset_NTIRE/Val/alignratio
>>>>>>> a9f4214f96656ec01266916956474969d63a8ee5
    condition: image

#### network structures
network_G:
  which_model_G: EPCE
  in_nc: 3
  out_nc: 3
  nf: 64
  act_type: relu

#### path
path:
  root: ./
<<<<<<< HEAD
  # pretrain_model_G: /home/jiaqitang/HDR_all/Final_Ours/experiments/Final_Ours-Original_archived_230627-142133/models/10000_G.pth
=======
  pretrain_model_G: /home/jiaqitang/HDR_all/Final_Ours/experiments/Final_Ours-Original_archived_230627-142133/models/10000_G.pth
>>>>>>> a9f4214f96656ec01266916956474969d63a8ee5
  strict_load: false
  # resume_state: /home/jiaqitang/HDR_all/Final_Ours/experiments/Final_Ours-Original/training_state/30000.state

#### training settings: learning rate scheme, loss
train:
<<<<<<< HEAD
  lr_G: !!float 1e-6
=======
  lr_G: !!float 1e-5
>>>>>>> a9f4214f96656ec01266916956474969d63a8ee5
  lr_scheme: MultiStepLR # MultiStepLR | CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 800000 # 600000
  warmup_iter: -1  # no warm up

  lr_steps: [200000, 400000, 600000, 800000]
  lr_gamma: 0.5

<<<<<<< HEAD
  pixel_criterion: tanh_l1
=======
  pixel_criterion: smooth_l1
>>>>>>> a9f4214f96656ec01266916956474969d63a8ee5
  # l1 | l2 | tanh_l1 | tanh_l2 / tanh_l1_Entropy
  pixel_weight: 1.0

  manual_seed: 20
<<<<<<< HEAD
  val_freq: !!float 500
=======
  val_freq: !!float 2000
>>>>>>> a9f4214f96656ec01266916956474969d63a8ee5

#### logger
logger:
  print_freq: 10
<<<<<<< HEAD
  save_checkpoint_freq: !!float 500
=======
  save_checkpoint_freq: !!float 10000
>>>>>>> a9f4214f96656ec01266916956474969d63a8ee5
